export const REQUEST_FOR_SAVE_USER_DATA = "REQUEST_FOR_USER_DATA";
export const SAVE_USER_DATA_SUCCESS_REQUEST = "SAVE_USER_DATA_SUCCESS_REQUEST";
export const SAVE_USER_DATA_FAILURE_REQUEST = "SAVE_USER_DATA_FAILURE_REQUEST"